services:
  - type: web
    name: bot2-condominio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT"
    envVars:
      - key: PORT
        value: "10000"
